# Generated by Django 2.2.6 on 2019-10-19 16:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20191019_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
