# Generated by Django 2.2.6 on 2019-10-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_newsitem_hacker_news_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='posted_on',
            field=models.CharField(default='', max_length=100),
        ),
    ]
