# Generated by Django 2.2.6 on 2019-10-20 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0005_auto_20191020_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='title',
            field=models.CharField(default='', max_length=500),
        ),
    ]
