# Generated by Django 2.2.6 on 2019-10-20 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_newsitem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsitem',
            name='url',
            field=models.CharField(default='', max_length=500, unique=True),
        ),
    ]
