# Generated by Django 2.2.6 on 2019-10-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_auto_20191021_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='contents',
            field=models.TextField(default=''),
        ),
    ]
