# Generated by Django 2.2.6 on 2019-10-24 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0009_newsitem_contents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsitem',
            name='contents',
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_site.NewsItem')),
            ],
        ),
    ]
