# Generated by Django 2.2.6 on 2019-10-24 07:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_site', '0010_auto_20191024_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsitem',
            name='users',
            field=models.ManyToManyField(related_name='reads', to=settings.AUTH_USER_MODEL, verbose_name='Readers'),
        ),
        migrations.DeleteModel(
            name='Page',
        ),
    ]
